#!/bin/bash

export ONEAPI_ROOT=<PATH TO ONEAPI INSTALLATION>
export ROCM_ROOT=<PATH TO ROCM INSTALLATION>
export HPCX_ROOT=<PATH TO HPCX INSTALLATION>
export CUDA_ROOT=<PATH TO CUDA INSTALLATION>
export ONEMATH_ROOT=<PATH TO ONEMATH INSTALLATION>
